### ISSUE TITLE
Forms and assetic

### ISSUE THREAD

**Issue by Bersman** [noiselabs/SmartyBundle#15]
Hi,

do you have any idea when you will continue with building for the form and assetic extension ?

**Comment by davidfuhr** [comment]
Are there any plans merging the form-extension branch into master? Is it still missing documentation and test suite?

**Comment by noisebleed** [comment]
@davidfuhr not just documentation but also the implementation is incomplete. @belka-ew has progressed further but I'm entirely aware of the current status of his work.

**Comment by vitorbrandao** [comment]
Forms and Assetic support has been dropped in the main branch. Closing.
