### ISSUE TITLE
Undefined property using form_widget

### ISSUE THREAD

**Issue by truckee** [noiselabs/SmartyBundle#22]
In v2.1.3, an attempt to create a form using a Smarty template and the symfony form object, the line
`{form_widget form=$form}`
results in the following:
"Notice: Undefined property: NoiseLabs\Bundle\SmartyBundle\Extension\FormExtension::$resources in G:\Documents\workspace\sym\vendor\noiselabs\smarty-bundle\NoiseLabs\Bundle\SmartyBundle\Extension\FormExtension.php line 325" in "G:\Documents\workspace\sym\src\Mana\AdminBundle/Resources/views/Client/client_addnew.html.tpl" 

Without the widget line the template appears as expected.

As an aside: I'm successfully using the default Smarty extension .tpl while in the Netbeans IDE.

**Comment by f5developper** [comment]
はようｗｗｗｗ

**Comment by Pr9nikVGB** [comment]
Hi guys, somebody found a solution to this problem??

**Comment by vitorbrandao** [comment]
Forms support has been dropped in the main branch and is currently out of scope for the next release. Closing.
