### ISSUE TITLE
Mopa Bootstrap a requirement?

### ISSUE THREAD

**Issue by code4pay** [noiselabs/SmartyBundle#35]
Hi did an upgrade and when I try to run symfony console commands I always get 

```
[InvalidArgumentException]                                                                                                                               
  Bundle "MopaBootstrapBundle" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file  
  ?         

```

which is correct it is not installed and I don't actually require it?
How do I turn this requirement off?
Thanks

**Comment by vitorbrandao** [comment]
MopaBootstrapBundle support has been dropped in https://github.com/noiselabs/SmartyBundle/pull/82. It is no longer a requirement.
