### ISSUE TITLE
Symfony 3.1 support?

### ISSUE THREAD

**Issue by eltomato89** [noiselabs/SmartyBundle#61]
Do you plan Symfony 3.1 support? Any ETA?

**Comment by noisebleed** [comment]
Hi @eltomato89, as I'm not using Symfony (and therefore SmartyBundle) actively these days upgrades to SmartyBundle have come mostly from contributors besides myself. I welcome you and others to contribute with merge requests for Symfony 3.1 support. 

Said that, I've started https://github.com/noiselabs/smarty-bundle-sandbox last weekend to help me test SmartyBundle with new Symfony versions and features. I'll kick off a feature branch for Symfony 3.1 support and we can track progress in this ticket.

**Comment by noisebleed** [comment]
@eltomato89 SmartyBundle v2.0.0 has just been released. Can you give it a try?
