### ISSUE TITLE
Question: Is this project abandoned?

### ISSUE THREAD

**Issue by ApertureDevelopment** [noiselabs/SmartyBundle#76]
I am asking because I saw that the last commits have been 3 years ago. But did you abandon this project?

**Comment by vitorbrandao** [comment]
Hello @ApertureDevelopmen. I have never flagged this project as abandoned although in hindsight I should have done so. I've done some work on trying to get this bundle compatible with the latest Symfony versions which unfortunately I was never able to finish. The reality is I'm not doing much work with either Symfony or PHP for some time now and I lack the time and motivation to keep this project updated. I'm sorry if you find this answer disappointing.

Are you interested in maintaining this project. I'm happy to transfer admin privileges.

Kind regards,
Vítor

**Comment by vitorbrandao** [comment]
I've decided to revive this project. Symfony 4 and 5 are currently targeted.
